dist: trusty
sudo: false

language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

before_install:
  - java -version
  - mvn --version

install:
  - mvn -s conf/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/029aeea7192da947a226
    on_success: change
    on_failure: always
    on_start: never
    on_cancel: always
    on_error: always
