language: java

before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip
  - unzip -qq apache-maven-3.5.0-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$M2_HOME/bin:$PATH
  # fix travis-ci/travis-ci#4629
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
install:
  - mvn -s conf/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8
