version: '{build}'
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn -s conf/settings.xml clean package
test_script:
  - mvn -s conf/settings.xml test
cache:
  - C:\maven
