# See documentation at http://dev.bukkit.org/server-mods/silkspawners/

consumeEgg: true
usePermissions: false
useWorldGuard: true
defaultCreature: null
spawnerCommandReachDistance: 6

minSilkTouchLevel: 1

destroyDropEgg: false
#destroyDropEgg: true
destroyDropXP: 0
#destroyDropXP: 1000
destroyDropBars: 0
#destroyDropBars: 8

craftableSpawners: false
spawnersUnstackable: false

verboseConfig: false
useExtraMobs: false
spawnEggOverride: false
dumpEntityMap: false

useSpout: true
notifyOnClick: true
notifyOnHold: true

# creatures: key is official creature type name, case-sensitive, from http://jd.bukkit.org/apidocs/org/bukkit/entity/CreatureType.html
# entityID is used in spawn eggs, from http://www.minecraftwiki.net/wiki/Data_values#Entity_IDs
# legacyID is pre-1222 creaturebox(+other plugins) scheme, see order on http://dev.bukkit.org/server-mods/creaturebox/pages/trading-mob-spawners/
creatures:
    Creeper: 
        entityID: 50
        legacyID: 5
        aliases: ['c', 'creep', 'cataclysm']
        enableCraftingSpawner: true
    Skeleton: 
        entityID: 51
        legacyID: 8
        aliases: ['s', 'sk', 'skelly', 'skellington']
        enableCraftingSpawner: true
    Spider: 
        entityID: 52
        legacyID: 9
        aliases: ['sp', 'bug']
        enableCraftingSpawner: true
    Giant: 
        entityID: 53
        legacyID: 13
        aliases: ['giantzombie']
        enableCraftingSpawner: true
    Zombie: 
        entityID: 54
        legacyID: 10
        aliases: ['z']
        enableCraftingSpawner: true
    Slime: 
        entityID: 55
        legacyID: 11
        aliases: ['sl']
        enableCraftingSpawner: true
    Ghast: 
        entityID: 56
        legacyID: 6
        aliases: ['g']
        enableCraftingSpawner: true
    PigZombie: 
        entityID: 57
        legacyID: 7
        aliases: ['pigman', 'zombiepigman', 'pg', 'zp']
        displayName: 'Zombie Pigman'
        enableCraftingSpawner: true
    Enderman: 
        entityID: 58
        legacyID: 16
        aliases: ['e', 'ender', 'endermen', 'slenderman']
        enableCraftingSpawner: true
    CaveSpider: 
        entityID: 59
        legacyID: 15
        aliases: ['cspider', 'cs', 'bluespider']
        displayName: 'Cave Spider'
        enableCraftingSpawner: true
    Silverfish: 
        entityID: 60
        legacyID: 17
        aliases: ['sf', 'fish']
        enableCraftingSpawner: true
    Blaze: 
        entityID: 61
        legacyID: 18
        aliases: ['b']
        enableCraftingSpawner: true
    LavaSlime: 
        entityID: 62
        legacyID: 20
        aliases: ['magmacube', 'mcube', 'magma', 'm', 'mc']
        displayName: 'Magma Cube'
        enableCraftingSpawner: true
    EnderDragon:
        entityID: 63
        legacyID: 19
        displayName: 'Enderdragon'
        aliases: ['dragon', 'raqreqentba']
        enableCraftingSpawner: true
    Pig: 
        entityID: 90
        legacyID: 0
        aliases: ['p']
        enableCraftingSpawner: true
    Sheep: 
        entityID: 91
        legacyID: 3
        aliases: ['sh']
        enableCraftingSpawner: true
    Cow: 
        entityID: 92
        legacyID: 2
        aliases: ['bovine']
        enableCraftingSpawner: true
    Chicken: 
        entityID: 93
        legacyID: 1
        aliases: ['chick', 'ch', 'bird']
        enableCraftingSpawner: true
    Squid: 
        entityID: 94
        legacyID: 4
        aliases: ['sq', 'octopus']
        enableCraftingSpawner: true
    #Monster:
    #   no entityID - this isn't real, and was removed in 1.1-R4
    #   aliases: ['human']
    #   legacyID: 12
    #   enableCraftingSpawner: true
    Wolf: 
        entityID: 95
        legacyID: 14
        aliases: ['w', 'dog']
        enableCraftingSpawner: true
    MushroomCow: 
        entityID: 96
        legacyID: 21
        displayName: 'Mooshroom'
        aliases: ['m', 'mcow']
        enableCraftingSpawner: true
    SnowMan: 
        entityID: 97
        legacyID: 22
        displayName: 'Snow Golem'
        aliases: ['golem', 'sgolem', 'sg', 'sm', 'snowmen']
        enableCraftingSpawner: true
    Ozelot:
        entityID: 98
        legacyID: 23
        displayName: 'Ocelot'
        aliases: ['ocelot', 'oce', 'o', 'cat', 'kitty']
        enableCraftingSpawner: true
    VillagerGolem:
        entityID: 99
        legacyID: 24
        displayName: 'Iron Golem'
        aliases: ['igolem', 'ironman', 'iron', 'ig']
        enableCraftingSpawner: true
    Villager: 
        entityID: 120
        legacyID: 23
        aliases: ['npc', 'v']
        enableCraftingSpawner: true
   
    # Modded mobs - if you're using 'useExtraMobs: true', comment/uncomment lines below as needed

    # Animal Bikes mod for MCPC 1.2.3 from http://www.mcportcentral.co.za/index.php?topic=1692.0
    # and http://www.minecraftforum.net/topic/762794-124-animal-bikes-v1111-sspsmp-added-iron-golem/
    # IMPORTANT: You have to mod your client and server as above before this will work.
    EntityCowBike:
        entityID: 159
        displayName: 'Cow Bike'
        aliases: ['cbike', 'cowb']
        enableCraftingSpawner: true
    EntitySpiderBike:
        entityID: 160
        displayName: 'Spider Bike'
        aliases: ['sbike', 'spbike', 'spiderb']
        enableCraftingSpawner: true
    EntityPigBike:
        entityID: 161
        displayName: 'Pig Bike'
        aliases: ['pbike', 'pigb']
        enableCraftingSpawner: true
    EntitySheepBike:
        entityID: 162
        displayName: 'Sheep Bike'
        aliases: ['shbike', 'sheepb']
        enableCraftingSpawner: true
    EntityChickenBike:
        entityID: 163
        displayName: 'Chicken Bike'
        aliases: ['chbike', 'chickenb']
        enableCraftingSpawner: true
    EntityWolfBike:
        entityID: 164
        displayName: 'Wolf Bike'
        aliases: ['wbike', 'wolfb']
        enableCraftingSpawner: true
    EntitySquidBike:
        entityID: 165
        displayName: 'Squid Bike'
        aliases: ['sqbike', 'squidb']
        enableCraftingSpawner: true
    EntityCreeperBike:
        entityID: 166
        displayName: 'Creeper Bike'
        aliases: ['crbike', 'creeperb']
        enableCraftingSpawner: true
    EntityPonyBike:
        entityID: 167
        displayName: 'Pony Bike'
        aliases: ['pobike', 'ponyb', 'pony', 'horse']
        enableCraftingSpawner: true
    EntityEndermanBike:
        entityID: 168
        displayName: 'Enderman Bike'
        aliases: ['ebike', 'enderb', 'endermanb', 'enderbike']
        enableCraftingSpawner: true
    EntityDragonBike:
        entityID: 169
        displayName: 'Dragon Bike'
        aliases: ['dbike', 'dragonb']
        enableCraftingSpawner: true
    EntityNotchBike:
        entityID: 170
        displayName: 'Notch Bike'
        aliases: ['nbike', 'notchb', 'notch']
        enableCraftingSpawner: true
    EntityReindeerBike:
        entityID: 171
        displayName: 'Reindeer Bike'
        aliases: ['rbike', 'reindeerb', 'reindeer', 'deer']
        enableCraftingSpawner: true
    EntitySnowGolemBike:
        entityID: 172
        displayName: 'Snow Golem Bike'
        aliases: ['sgbike', 'snowbike', 'snowgolemb', 'sgolemb', 'snowgollembike', 'snowgolembike']
        enableCraftingSpawner: true
    EntityGhastBike:
        entityID: 173
        displayName: 'Ghast Bike'
        aliases: ['gbike', 'ghastb']
        enableCraftingSpawner: true
    EntityIronmanBike:
        entityID: 174
        displayName: 'Iron Golem Bike'
        aliases: ['igbike', 'irongolemb', 'igolemb']
        enableCraftingSpawner: true

    # Natural Selection mod for CraftBukkit 1.1-R4 from http://www.mcportcentral.co.za/index.php?topic=1360.0
    # and http://www.minecraftforum.net/topic/950329-110smpforgenatural-selection-a-minecraft-survival-accession-v21/
    # IMPORTANT: You have to mod your client and server as above before this will work.
#    Buck:
#        entityID: 166
#        aliases: ['maledeer', 'mdeer']
#        enableCraftingSpawner: true
#    Doe:
#        entityID: 167
#        aliases: ['femaledeer', 'fdeer', 'deer']
#        enableCraftingSpawner: true
#    Tom:
#        entityID: 168
#        aliases: ['maleturkey', 'mturkey']
#        enableCraftingSpawner: true
#    Hen:
#        entityID: 169
#        aliases: ['femaleturkey', 'fturkey', 'turkey']
#        enableCraftingSpawner: true
#    Grizzly:
#        entityID: 170
#        aliases: ['bear']
#        enableCraftingSpawner: true
#    Boar:
#        entityID: 171
#        aliases: ['wildpig']
#        enableCraftingSpawner: true
#    Dingo:
#        entityID: 173       # no 172?
#        enableCraftingSpawner: true
#    Magicman:
#        entityID: 174
#        aliases: ['magician']
#        enableCraftingSpawner: true

    # Rancraft Penguins 1.2.5f mod for CraftBukkit 1.2.5 from http://www.mcportcentral.co.za/index.php?topic=2491.0
    # and http://www.minecraftforum.net/topic/910095-125-rancraft-penguins-seven-species-mlmp-forge-bukkit/
    # IMPORTANT: You have to mod your client and server as above before this will work.
    Little Blue Penguin:
        entityID: 16
        aliases: ['lbpenguin', 'lpenguin', 'littlepenguin', 'bluepenguin', 'bpenguin', 'littleblue', 'lbp', 'lp']
        enableCraftingSpawner: true
    Flame Penguin:
        entityID: 17
        aliases: ['fpenguin', 'fp']
        enableCraftingSpawner: true
    King Penguin:
        entityID: 18
        aliases: ['kpenguin', 'kp']
        enableCraftingSpawner: true
    Yellow-Eyed Penguin:
        entityID: 19
        aliases: ['ypenguin', 'yp']
        enableCraftingSpawner: true
    Magellanic Penguin:
        entityID: 20
        aliases: ['mpenguin', 'mp']
        enableCraftingSpawner: true
    Adelie Penguin:
        entityID: 21        # interestingly, this is the same as FallingSand.. but it doesn't seem to conflict(?)
        aliases: ['apenguin', 'ap']
        enableCraftingSpawner
    Emperor Penguin:
        entityID: 87
        aliases: ['epenguin', 'emperor', 'ep', 'penguin', 'peng']
        enableCraftingSpawner: true
